spring:
    application:
        name: graindepot-eureka
    jmx:
        enabled: false
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 10000

server:
    port: 8761 #启动端口

eureka:
    client:
        registerWithEureka: false  #false:不作为一个客户端注册到注册中心
        fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
    server:
        enableSelfPreservation: true #关闭自我保护 false
        #evictionIntervalTimerInMs: 5000 #清理无效节点的时间间隔，默认60秒